import asyncio, json
from playwright.async_api import async_playwright
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch()
        ctx = await b.new_context(viewport={'width':390,'height':844}, device_scale_factor=2, timezone_id='America/Toronto')
        page = await ctx.new_page()
        errs=[]; page.on('pageerror', lambda e: errs.append(str(e))); page.on('console', lambda m: m.type=='error' and errs.append(m.text))
        await page.goto('http://localhost:8765/?fixture=1#teams=398263,398262')
        await page.wait_for_timeout(800)
        await page.screenshot(path='test/1-upcoming.png', full_page=True)
        print('upcoming cards', await page.locator('.card').count())
        print(await page.locator('.card').first.inner_text())
        await page.click('.arena >> nth=0'); await page.wait_for_timeout(300)
        await page.screenshot(path='test/2-rink.png')
        print('rink:', await page.locator('#rinkList').inner_text())
        await page.click('#rinkClose')
        await page.click('[data-view=results]'); await page.wait_for_timeout(200)
        print('results cards', await page.locator('.card').count())
        await page.screenshot(path='test/3-results.png', full_page=True)
        await page.click('[data-view=teams]'); await page.wait_for_timeout(200)
        await page.fill('#teamSearch','u14a'); await page.wait_for_timeout(200)
        print('team rows', await page.locator('.team-row').count(), 'checked', await page.locator('.team-row.on').count())
        await page.screenshot(path='test/4-teams.png', full_page=True)
        print('tracked LS', await page.evaluate("localStorage.getItem('rt.tracked')"))
        await page.emulate_media(color_scheme='dark')
        await page.click('[data-view=upcoming]'); await page.wait_for_timeout(200)
        await page.screenshot(path='test/5-dark.png')
        print('errors', errs)
        await b.close()
asyncio.run(main())
